# WARNING: you are on the master branch, please refer to the examples on the branch that matches your `cortex version`

- name: iris-classifier
  id: id
  key: key
  metadata_root: metadata_root
  endpoint: endpoint
  predictor:
    type: python
    path: predictor.py
    again: agq
    config:
      model: s3://cortex-examples/pytorch/iris-classifier/weights.pth

